### ISSUE TITLE
golang suppot yet ?

### ISSUE THREAD

**Issue by ghost** [ontio/ontology-wasm#5]
This runtime looks pretyt neat.

At the moment it supports c, rust and cpp.
But i think that the golang --> wasm code is now supported.

Might be worth trying out it.

I am trying to work out how to test it with your current code base.
Its a bit difficult because you dont have any cmd folder or cli yet ?

**Comment by JasonZhouPW** [comment]
the cli will be added in next version,you can write some testcase with your compiled wasm code for now.
